todoapp/app/urls.py
from django.urls import path, include

from .views import *

app_name = 'app'

url_app_pattern = [
    path('/', HomePage.as_view(), name='home_page'),
    path('post/addpost/', AddPost.as_view(), name='add_post'),
    path('post/<slug:post_slug>/', PostPage.as_view(), name='post_url'),
    path('post/<slug:post_slug>/update/', ChangePostView.as_view(), name='update_post_url'),
    path('post/<slug:post_slug>/delete/', DeletePostView.as_view(), name='delete_post_url'),
    path('post/<slug:post_slug>/like/', LikeView, name='like_post_url'),
    path('post/result/search/', SearchForm, name='search_url'),
    path('post/<slug:post_slug>/delete/<int:comment_id>/', DeleteComment, name='delete_comment_url'),
    path('post/<slug:post_slug>/like/<int:comment_id>/', LikeCommentView, name='like_comment_url'),
]

todoapp/todoapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from app.urls import url_app_pattern
from users.urls import url_users_pattern

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include((url_app_pattern, 'app'), namespace='app')),
    path('user/', include((url_users_pattern, 'users'), namespace='users')),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todoapp/users/urls.py
from django.urls import path

from .views import *

url_users_pattern = [
    path('login/', LoginUser.as_view(), name='login_url'),
    path('logout/', LogoutView.as_view(), name='logout_url'),
    path('register/', RegisterUserView.as_view(), name='register_url'),
    path('profile/<slug:user_slug>', ProfileView.as_view(), name='profile_url'),
    path('profile/<slug:user_slug>/update', UpdateProfile.as_view(), name='update_profile_url'),
]

todoapp/users/models.py
from autoslug import AutoSlugField
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class CustomUser(AbstractUser):
    bio = models.TextField(max_length=255, null=True, blank=True)
    date_b = models.DateField(null=True, blank=True)
    slug = AutoSlugField(populate_from='username', unique=True)
    head_image = models.ImageField(upload_to='media/', null=True, blank=True)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse("profile_url", kwargs={"user_slug": self.slug})

todoapp/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm, PasswordChangeForm

from .models import *


class RegisterCustomUser(UserCreationForm):
    username = forms.CharField(label='Никнейм')
    email = forms.EmailField(label='Почта')
    password1 = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'password1', 'password2')


class LoginUserForm(AuthenticationForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'password')


class UpdateUserForm(UserChangeForm):
    head_image = forms.ImageField(label='Аватар')
    username = forms.CharField(label='Никнейм')
    bio = forms.Textarea()
    email = forms.EmailField(label='Почта')
    date_b = forms.DateInput()

    class Meta:
        model = CustomUser
        fields = ('head_image', 'username', 'bio', 'email', 'date_b')


class ChangePasswordUser(PasswordChangeForm):
    old_password = forms.CharField(widget=forms.PasswordInput)
    new_password1 = forms.CharField(widget=forms.PasswordInput)
    new_password2 = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = CustomUser
        fields = ('old_password', 'new_password1', 'new_password2')

todoapp/users/views.py
from django.contrib.auth import login
from django.contrib.auth.views import LoginView
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, UpdateView

from .forms import *


# Create your views here.
class RegisterUserView(CreateView):
    form_class = RegisterCustomUser
    template_name = 'register_user.html'

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        # TODO: поменять на профиль
        return redirect('home_page')


class LoginUser(LoginView):
    authentication_form = LoginUserForm
    template_name = 'login_user.html'
    # TODO: поменять на профиль
    success_url = reverse_lazy('home_page')


class UpdateProfile(UpdateView):
    form_class = UpdateUserForm
    # TODO: поменять на профиль
    template_name = 'update_user.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["customuser"] = self.request.user
        return context

    def put(self, request, user_slug):
        print('put')
        form = UpdateUserForm(request.PUT, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('profile_url', user_slug)

    def get_object(self):
        return self.request.user


class ResetPassword(UpdateView):
    form_class = ChangePasswordUser
    template_name = 'change_password.html'
    # TODO: поменять на профиль
    success_url = reverse_lazy('home_page')


class ProfileView(DetailView):
    model = CustomUser
    template_name = 'profile_page.html'
    context_object_name = 'customuser'
    slug_url_kwarg = 'user_slug'

todoapp/users/templates/login_user.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel='stylesheet' href='{% static "users/css/login.css" %}'>
    <link rel="stylesheet" href="{% static 'users/fonts/font.css' %}">
    <title>Вход</title>
</head>
<body>
    <div class="container">
        <form action="{% url 'users:login_url' %}" method="post">
            {% csrf_token %}
            {{ form.non_field_errors }}
            {% for f in form %}
            <p><label id='{{ f.id_for_label }}'>{{ f.label }}</label><br>{{ f }}</p>
            {% endfor %}
            <button type='submit'>Войти</button>
            <a href='{% url "users:register_url" %}'>Нет акканута?</a>
        </form>
    </div>
</body>
</html>

todoapp/users/templates/profile_page.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ customuser.username }}</title>
    <link rel="stylesheet" href="{% static 'users/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'users/fonts/font.css' %}">
</head>
<body>
    <div class="container">
        <nav class="navbar">
            <ul class='third-ul'>
                <li><a class='last-link' href="{% url 'app:home_page' %}"><img src="{% static 'app/images/logo.jpg' %}" alt="..." width="60px"
                    height="60px"></a></li>
            </ul>
            <ul class='first-ul'>
                <li class='direct'><a href="{% url 'app:home_page' %}">Главная страница</a></li>
                <li class='direct'><a href="#">О нас</a></li>
                <li class='direct'><a href="#">Помощь</a></li>
                <li><a href="{% url 'app:add_post' %}">Создать задачу</a></li>
            </ul>
            {% if not user.is_authenticated %}
            <ul class='second-ul'>
                <li><a class='last-link' href="{% url 'users:login_url' %}">Войти</a></li>
            </ul>
            {% else %}
            <ul class='second-ul'>
                <li><a class='last-link' href="#">{{ user.username }}</a></li>
            </ul>
            {% endif %}
        </nav>
        <div class="content-block">
            {% if customuser.head_image %}
                <div class="avatar">
                    <img src={{ customuser.head_image.url }} alt="...">
                </div>
            {% else %}
                <div class="avatar">
                    <img src="{% static 'users/images/non-auth.png' %}" alt="...">
                </div>
            {% endif %}
            <div class="information">
                <p class="username">{{ customuser.username }}</p>
                {% if customuser.bio %}
                    <p class="bio">{{ customuser.bio }}</p>
                {% else %}
                    <p class="bio">Not bio yet.</p>
                {% endif %}
                <p class="date_j">{{ customuser.date_joined }}</p>
                {% if customuser.date_b %}
                    <p class="date_b">Дата рождения: {{ customuser.date_b }}</p></br>
                {% endif %}
                <a href="{% url 'users:update_profile_url' customuser.slug %}">Редактировать профиль</a>
                <form action="{% url 'users:logout_url' %}" method='post'>
                    {% csrf_token %}
                    <button type='submit'>Выйти</button>
                </form>
            </div>
        </div>
        <h2>Посты пользователя:</h2>
            {% for p in posts %}
            <a href='{% url "app:post_url" p.slug %}'>{{ p.title }}</br></br></a>
            {% endfor %}
    </div>
</body>
</html>

todoapp/users/templates/register_user.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel='stylesheet' href='{% static "users/css/login.css" %}'>
    <link rel="stylesheet" href="{% static 'users/fonts/font.css' %}">
    <title>Регистрация</title>
</head>
<body>
    <div class="container">
        <form action="{% url 'users:register_url' %}" method="post">
            {% csrf_token %}
            {{ form.non_field_errors }}
            {% for f in form %}
            <p><label id='{{ f.id_for_label }}'>{{ f.label }}</label><br>{{ f }}</p>
            <p>{{ f.errors }}</p>
            {% endfor %}
            <button type='submit'>Регистрация</button>
        </form>
    </div>
</body>
</html>

todoapp/users/templates/update_user.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel='stylesheet' href='{% static "users/css/login.css" %}'>
    <link rel="stylesheet" href="{% static 'users/fonts/font.css' %}">
    <title>Редактирование профиля</title>
</head>
<body>
    <div class="container">
        <form method='post' enctype='multipart/form-data'>
            {% csrf_token %}
            {{ form.non_field_error }}
            {% for f in form %}
            {% if not forloop.last %}
            <p><label id='{{ f.id_for_label }}'>{{ f.label }}</label><br>{{ f }}</p>
            {{ f.add_error }}
            {% endif %}
            {% endfor %}
            <button type='submit'>Сохранить</button>
        </form>
    </div>
</body>
</html>