todoapp/app/urls.py
from django.urls import path, include

from .views import *

app_name = 'app'

url_app_pattern = [
    path('/', HomePage.as_view(), name='home_page'),
    path('post/addpost/', AddPost.as_view(), name='add_post'),
    path('post/<slug:post_slug>/', PostPage.as_view(), name='post_url'),
    path('post/<slug:post_slug>/update/', ChangePostView.as_view(), name='update_post_url'),
    path('post/<slug:post_slug>/delete/', DeletePostView.as_view(), name='delete_post_url'),
    path('post/<slug:post_slug>/like/', LikeView, name='like_post_url'),
    path('post/result/search/', SearchForm, name='search_url'),
    path('post/<slug:post_slug>/delete/<int:comment_id>/', DeleteComment, name='delete_comment_url'),
    path('post/<slug:post_slug>/like/<int:comment_id>/', LikeCommentView, name='like_comment_url'),
]

todoapp/todoapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from app.urls import url_app_pattern
from users.urls import url_users_pattern

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include((url_app_pattern, 'app'), namespace='app')),
    path('user/', include((url_users_pattern, 'users'), namespace='users')),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todoapp/users/urls.py
from django.urls import path

from .views import *

url_users_pattern = [
    path('login/', LoginUser.as_view(), name='login_url'),
    path('logout/', LogoutView.as_view(), name='logout_url'),
    path('register/', RegisterUserView.as_view(), name='register_url'),
    path('profile/<slug:user_slug>', ProfileView.as_view(), name='profile_url'),
    path('profile/<slug:user_slug>/update', UpdateProfile.as_view(), name='update_profile_url'),
]

todoapp/app/templates/add_post.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Добавление поста</title>
    <link rel="stylesheet" href="{% static 'app/css/home_page.css' %}">
    <link rel="stylesheet" href="{% static 'app/fonts/font.css' %}">
</head>
<body>
    <div class="container">
        <nav class="navbar">
            <ul class='third-ul'>
                <li><a class='last-link' href="#"><img src="{% static 'app/images/logo.jpg' %}" alt="..." width="60px"
                    height="60px"></a></li>
            </ul>
            <ul class='first-ul'>
                <li class='direct'><a href="{% url 'app:home_page' %}">Главная страница</a></li>
                <li class='direct'><a href="#">Завершенные задачи</a></li>
                <li><a href="{% url 'app:add_post' %}">Создать задачу</a></li>
            </ul>
            {% if not user.is_authenticated %}
            <ul class='second-ul'>
                <li><a class='last-link' href="#">Войти</a></li>
            </ul>
            {% else %}
            <ul class='second-ul'>
                <li><a class='last-link' href="#">{{ user.username }}</a></li>
            </ul>
            {% endif %}
        </nav>
        <div class="div-form">
            <form action="{% url 'app:add_post' %}"  method='post' enctype='multipart/form-data'>
                {% csrf_token %}
                {{ form.non_field_errors }}

                {% for f in form %}
                <p><label id='{{ f.id_for_label }}'>{{ f.label }}</label><br>{{ f }}</p>
                {% endfor %}
                <button type='submit'>Создать</button>
            </form>
        </div>
    </div>
</body>
</html>

todoapp/app/templates/change_post.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Изменение поста</title>
    <link rel="stylesheet" href="{% static 'app/css/home_page.css' %}">
    <link rel="stylesheet" href="{% static 'app/fonts/font.css' %}">
</head>
<body>
    <div class="container">
        <nav class="navbar">
            <ul class='third-ul'>
                <li><a class='last-link' href="{% url 'app:home_page' %}"><img src="{% static 'app/images/logo.jpg' %}" alt="..." width="60px"
                    height="60px"></a></li>
            </ul>
            <ul class='first-ul'>
                <li class='direct'><a href="{% url 'app:home_page' %}">Главная страница</a></li>
                <li class='direct'><a href="#">О нас</a></li>
                <li class='direct'><a href="#">Помощь</a></li>
                <li><a href="{% url 'app:add_post' %}">Создать задачу</a></li>
            </ul>
            {% if not user.is_authenticated %}
            <ul class='second-ul'>
                <li><a class='last-link' href="#">Войти</a></li>
            </ul>
            {% else %}
            <ul class='second-ul'>
                <li><a class='last-link' href="{% url 'users:profile_url' user.slug %}">{{ user.username }}</a></li>
            </ul>
            {% endif %}
        </nav>
        <div class="div-form">
            <form action="{% url 'app:update_post_url' post.slug %}"  method='post' enctype='multipart/form-data'>
                {% csrf_token %}
                {{ form.non_field_errors }}
                {% for f in form %}
                <p><label id='{{ f.id_for_label }}'>{{ f.label }}</label><br>{{ f }}</p>
                <p>{{ f.errors }}</p>
                {% endfor %}
                <button type='submit'>Сохранить</button>
            </form>
        </div>
    </div>
</body>
</html>

todoapp/app/templates/home_page.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Главная страница</title>
    <link rel="stylesheet" href="{% static 'app/css/home_page.css' %}">
    <link rel="stylesheet" href="{% static 'app/fonts/font.css' %}">
</head>
<body>
    <div class="container">
        <nav class="navbar">
            <ul class='third-ul'>
                <li><a class='last-link' href="{% url 'app:home_page' %}"><img src="{% static 'app/images/logo.jpg' %}" alt="..." width="60px"
                    height="60px"></a></li>
            </ul>
            <ul class='first-ul'>
                <li class='direct'><a href="{% url 'app:home_page' %}">Главная страница</a></li>
                <li class='direct'><a href="#">О нас</a></li>
                <li class='direct'><a href="#">Помощь</a></li>
                <li><a href="{% url 'app:add_post' %}">Создать задачу</a></li>
            </ul>
            {% if not user.is_authenticated %}
            <ul class='second-ul'>
                <li><a class='last-link' href="{% url 'users:login_url' %}">Войти</a></li>
            </ul>
            {% else %}
            <ul class='second-ul'>
                <li><a class='last-link' href="{% url 'users:profile_url' customuser.slug %}">{{ user.username }}</a></li>
            </ul>
            {% endif %}
        </nav>
        <form method='get' action="{% url 'app:search_url' %}">
            <input type='text' name='q' placeholder='Введите название поста'></input>
            <button type='submit'>Искать</button>
        </form>
        {% for p in posts %}
        <div class="content-block">            
                {% if p.header_image %}
                <div class="content-img">
                    <a href="{% url 'app:post_url' p.slug %}"><img src="{{ p.header_image.url }}" alt="..." width="250px" height="250px"></a>
                </div>
                {% endif %}
                <div class='content-text'>
                    <a href="{% url 'app:post_url' p.slug %}"><p class="title">{{ p.title }}</p></a>
                    <p class="description">{{ p.body }}</p>
                    <div class="pre-last-data">
                        <div class="last-data">
                            <p class="data">{{ p.date_create }}</p>
                            <p class="author">{{ p.author }}</p>
                        </div>
                    </div>
                </div>        
        </div>
        {% endfor %}
    </div>
</body>
</html>

todoapp/app/templates/post_page.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ post.title }}</title>
    <link rel="stylesheet" href="{% static 'users/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'users/fonts/font.css' %}">
</head>
<body>
    <div class="container">
        <nav class="navbar">
            <ul class='third-ul'>
                <li><a class='last-link' href="{% url 'app:home_page' %}"><img src="{% static 'app/images/logo.jpg' %}" alt="..." width="60px"
                    height="60px"></a></li>
            </ul>
            <ul class='first-ul'>
                <li class='direct'><a href="{% url 'app:home_page' %}">Главная страница</a></li>
                <li class='direct'><a href="#">О нас</a></li>
                <li class='direct'><a href="#">Помощь</a></li>
                <li><a href="{% url 'app:add_post' %}">Создать задачу</a></li>
            </ul>
            {% if not user.is_authenticated %}
            <ul class='second-ul'>
                <li><a class='last-link' href="{% url 'users:login_url' %}">Войти</a></li>
            </ul>
            {% else %}
            <ul class='second-ul'>
                <li><a class='last-link' href="{% url 'users:profile_url' customuser.slug %}">{{ user.username }}</a></li>
            </ul>
            {% endif %}
        </nav>
        <div class="content-block">
            {% if post.header_image %}
                <div class="avatar">
                    <img src={{ post.header_image.url }} alt="...">
                </div>
            {% endif %}
            <div class="information">
                <p class="username">{{ post.title }}</p>
                {% if post.body %}
                    <p class="bio">{{ post.body }}</p>
                {% else %}
                    <p class="bio"></p>
                {% endif %}
                <p class="date_j">Дата создания: {{ post.date_create }}</p>
                <p class="date_j">Дата обновления:{{ post.date_update }}</p>
                <p class="date_b">Автор: {{ post.author }}</p>
                <br>
                <a href="{% url 'app:update_post_url' post.slug %}">Редактировать</a>
                <form method='post' action='{% url "app:delete_post_url" post.slug %}'>
                    {% csrf_token %}
                    <button type='submit'>Удалить</button>
                </form>
                <form action='{% url "app:like_post_url" post.slug %}' method='post'>
                    {% csrf_token %}
                    <button type='submit'>Лайк {{ post.like.count }}</button>
                </form>
                {% comment %} <a href='{% url "delete_comment_url" post.slug comment.id %}'>Удалить</a> {% endcomment %}
            </div>
            
        </div>
        <form action='{% url "app:post_url" post.slug %}' method='post'>
            {% csrf_token %}
            <p><label id='{{ form.body.id_for_label }}'></label>{{ form.body }}</p>
            <button type='submit'>Отправить</button>
        </form>
        <div class='comments'>
            {% if not post.comments.all %}
                <p>Not comments else!</p>
            {% else %}
                {% for c in post.comments.all %}
                <p>Автор {{ c.author }}</p>
                <p>{{ c.body }}</p>
                <p>{{ c.date_create }}</p>
                <form action='{% url "app:like_comment_url" post.slug c.id %}' method='post'>
                    {% csrf_token %}
                    <button type='submit'>Лайк {{ c.like.count }}</button>
                </form>
                <form method='post' action='{% url "app:delete_comment_url" post.slug c.id %}'>
                    {% csrf_token %}
                    <button type='submit'>Удалить</button>
                </form>
                <hr>
                {% endfor %}
            {% endif %}
        </div>
    </div>
</body>
</html>

todoapp/app/templates/search_result.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Результат</title>
    <link rel="stylesheet" href="{% static 'app/css/home_page.css' %}">
    <link rel="stylesheet" href="{% static 'app/fonts/font.css' %}">
</head>
<body>
    <div class="container">
        <nav class="navbar">
            <ul class='third-ul'>
                <li><a class='last-link' href="{% url 'app:home_page' %}"><img src="{% static 'app/images/logo.jpg' %}" alt="..." width="60px"
                    height="60px"></a></li>
            </ul>
            <ul class='first-ul'>
                <li class='direct'><a href="{% url 'app:home_page' %}">Главная страница</a></li>
                <li class='direct'><a href="#">О нас</a></li>
                <li class='direct'><a href="#">Помощь</a></li>
                <li><a href="{% url 'app:add_post' %}">Создать задачу</a></li>
            </ul>
            {% if not user.is_authenticated %}
            <ul class='second-ul'>
                <li><a class='last-link' href="{% url 'users:login_url' %}">Войти</a></li>
            </ul>
            {% else %}
            <ul class='second-ul'>
                <li><a class='last-link' href="{% url 'users:profile_url' customuser.slug %}">{{ user.username }}</a></li>
            </ul>
            {% endif %}
        </nav>
        {% if posts %}
            {% for p in posts %}
            <div class="content-block">            
                    {% if p.header_image %}
                    <div class="content-img">
                        <a href="{% url 'app:post_url' p.slug %}"><img src="{{ p.header_image.url }}" alt="..." width="250px" height="250px"></a>
                    </div>
                    {% endif %}
                    <div class='content-text'>
                        <a href="{% url 'app:post_url' p.slug %}"><p class="title">{{ p.title }}</p></a>
                        <p class="description">{{ p.body }}</p>
                        <div class="pre-last-data">
                            <div class="last-data">
                                <p class="data">{{ p.date_create }}</p>
                                <p class="author">{{ p.author }}</p>
                            </div>
                        </div>
                    </div>        
            </div>
            {% endfor %}
        {% else %}
        <p>Таких постов нет(</p>
        {% endif %}
    </div>
</body>
</html>